"""
===========================================================
Distribution System State Estimator
Stage 3

Reads PMU measurements generated by the PMU simulator and
constructs

1. Measurement Vector (z)
2. Initial State Vector (x)
3. Predicted Measurement Vector h(x)
4. Residual Vector r = z - h(x)

The WLS solver, Jacobian, Gain Matrix and Chi-Square
Bad Data Detection will be added in subsequent stages.

===========================================================
"""

import numpy as np
import pandas as pd

from network_model import NUM_BUSES
from measurement_model import measurement_model


class StateEstimator:

    ########################################################
    # Constructor
    ########################################################

    def __init__(self, csv_file):

        self.csv_file = csv_file

        # Load PMU data
        self.df = pd.read_csv(csv_file)

        # Measurement Vector
        self.z = None

        # State Vector
        self.x = None

        # Predicted Measurements
        self.h = None

        # Residual
        self.residual = None


    ########################################################
    # Measurement Vector
    ########################################################

    def build_measurement_vector(self):
        """
        Construct the measurement vector from the latest PMU
        snapshot.

        Measurement Order

        z =

        [
            PMU1 Voltage Magnitude
            PMU1 Voltage Phase
            PMU1 Current Magnitude
            PMU1 Current Phase

            PMU2 Voltage Magnitude
            PMU2 Voltage Phase
            PMU2 Current Magnitude
            PMU2 Current Phase

            PMU3 Voltage Magnitude
            PMU3 Voltage Phase
            PMU3 Current Magnitude
            PMU3 Current Phase
        ]
        """

        latest = self.df.iloc[-1]

        measurements = []

        for bus in range(1, NUM_BUSES + 1):

            measurements.extend([

                latest[f"PMU{bus} Voltage Magnitude"],
                latest[f"PMU{bus} Voltage Phase"],

                latest[f"PMU{bus} Current Magnitude"],
                latest[f"PMU{bus} Current Phase"]

            ])

        self.z = np.array(measurements)

        return self.z


    ########################################################
    # Initial State
    ########################################################

    def initialize_state(self):
        """
        Initial State Estimate

        x =

        [
            V1 θ1
            V2 θ2
            ...
            VN θN
        ]

        Flat Start

            Voltage Magnitude = 1.0 pu
            Voltage Angle     = 0 deg
        """

        self.x = np.zeros(2 * NUM_BUSES)

        for bus in range(NUM_BUSES):

            self.x[2 * bus] = 1.0
            self.x[2 * bus + 1] = 0.0

        return self.x


    ########################################################
    # Measurement Prediction
    ########################################################

    def predict_measurements(self):
        """
        Compute predicted measurements

            h(x)

        Currently delegated to measurement_model.py

        Later this function will compute

            I = Ybus · V

        internally.
        """

        self.h = measurement_model(self.x)

        return self.h


    ########################################################
    # Residual
    ########################################################

    def compute_residual(self):
        """
        Residual

            r = z - h(x)
        """
        print("z shape :", self.z.shape)
        print("h shape :", self.h.shape)

        self.residual = self.z - self.h

        return self.residual


    ########################################################
    # Summary
    ########################################################

    def summary(self):

        print("\n================================================")
        print(" Distribution System State Estimator")
        print("================================================")

        print("\nMeasurement Vector (z)\n")
        print(self.z)

        print("\nInitial State Vector (x0)\n")
        print(self.x)

        print("\nPredicted Measurement h(x)\n")
        print(self.h)

        print("\nResidual Vector r = z - h(x)\n")
        print(self.residual)

        print("\nMeasurement Dimension :", len(self.z))
        print("State Dimension       :", len(self.x))

        print("================================================")


    ########################################################
    # Main Flow
    ########################################################

    def run(self):

        print("\nBuilding measurement vector...")
        self.build_measurement_vector()

        print("Initializing state vector...")
        self.initialize_state()

        print("Predicting measurements...")
        self.predict_measurements()

        print("Computing residual...")
        self.compute_residual()

        self.summary()