"""
===========================================================
Distribution System State Estimator
Stage 3

Reads PMU measurements generated by the PMU simulator and
constructs

1. Measurement Vector (z)
2. Initial State Vector (x)
3. Predicted Measurement Vector h(x)
4. Residual Vector r = z - h(x)

The implementation now includes iterative WLS estimation,
analytical Jacobian computation, and chi-square-based
validation.

===========================================================
"""

import numpy as np
import pandas as pd

from network_model import NUM_BUSES
from measurement_model import measurement_model


class StateEstimator:

    ########################################################
    # Constructor
    ########################################################

    def __init__(self, csv_file):

        self.csv_file = csv_file

        # Load PMU data
        self.df = pd.read_csv(csv_file)

        # Measurement Vector
        self.z = None

        # State Vector
        self.x = None

        # Predicted Measurements
        self.h = None

        # Residual
        self.residual = None

        # Measurement labels for localization
        self.measurement_names = []

        # Synchronization offsets used for the current run
        self.sync_offsets_used = {}

    ########################################################
    # Measurement Vector
    ########################################################

    def build_measurement_vector(self, apply_sync_correction=False):
        """
        Construct the measurement vector from the latest PMU
        snapshot.

        Measurement Order

        z =

        [
            PMU1 Voltage Magnitude
            PMU1 Voltage Phase
            PMU1 Current Magnitude
            PMU1 Current Phase

            PMU2 Voltage Magnitude
            PMU2 Voltage Phase
            PMU2 Current Magnitude
            PMU2 Current Phase

            PMU3 Voltage Magnitude
            PMU3 Voltage Phase
            PMU3 Current Magnitude
            PMU3 Current Phase
        ]
        """

        latest = self.df.iloc[-1]

        measurements = []
        self.measurement_names = []
        self.sync_offsets_used = {}

        for bus in range(1, NUM_BUSES + 1):

            voltage_magnitude = latest[f"PMU{bus} Voltage Magnitude"]
            voltage_phase = latest[f"PMU{bus} Voltage Phase"]
            current_magnitude = latest[f"PMU{bus} Current Magnitude"]
            current_phase = latest[f"PMU{bus} Current Phase"]

            offset = 0.0
            if apply_sync_correction:
                offset = latest.get(f"PMU{bus} Sync Offset", 0.0)
                if pd.isna(offset):
                    offset = 0.0
                voltage_phase = voltage_phase - offset
                current_phase = current_phase - offset

            self.sync_offsets_used[f"PMU{bus}"] = float(offset)

            measurements.extend([
                voltage_magnitude,
                voltage_phase,
                current_magnitude,
                current_phase,
            ])

            self.measurement_names.extend([
                f"PMU{bus} Voltage Magnitude",
                f"PMU{bus} Voltage Phase",
                f"PMU{bus} Current Magnitude",
                f"PMU{bus} Current Phase",
            ])

        self.z = np.array(measurements, dtype=float)

        ########################################################
        # Convert measured angles from degrees to radians
        ########################################################

        # Voltage angles
        self.z[1::4] = np.deg2rad(self.z[1::4])

        # Current angles
        self.z[3::4] = np.deg2rad(self.z[3::4])

        return self.z

    ########################################################
    # Initial State
    ########################################################

    def initialize_state(self, apply_sync_correction=False):

        latest = self.df.iloc[-1]

        state = []

        for bus in range(1, NUM_BUSES + 1):

            voltage_phase = latest[f"PMU{bus} Voltage Phase"]

            if apply_sync_correction:
                offset = latest.get(f"PMU{bus} Sync Offset", 0.0)
                if pd.isna(offset):
                    offset = 0.0
                voltage_phase = voltage_phase - offset

            state.extend([
                latest[f"PMU{bus} Voltage Magnitude"],
                np.deg2rad(voltage_phase),
            ])

        self.x = np.array(state)

        return self.x

    ########################################################
    # Measurement Prediction
    ########################################################

    def predict_measurements(self):
        """
        Compute predicted measurements

            h(x)

        Currently delegated to measurement_model.py

        Later this function will compute

            I = Ybus · V

        internally.
        """

        self.h = measurement_model(self.x)

        return self.h

    ########################################################
    # Residual
    ########################################################

    def compute_residual(self):
        """
        Residual

            r = z - h(x)
        """

        self.residual = self.z - self.h

        return self.residual

    ########################################################
    # Summary
    ########################################################

    def summary(self):

        z_print = self.z.copy()
        h_print = self.h.copy()
        r_print = self.residual.copy()
        x_print = self.x.copy()

        z_print[1::4] = np.rad2deg(z_print[1::4])
        z_print[3::4] = np.rad2deg(z_print[3::4])

        h_print[1::4] = np.rad2deg(h_print[1::4])
        h_print[3::4] = np.rad2deg(h_print[3::4])

        r_print[1::4] = np.rad2deg(r_print[1::4])
        r_print[3::4] = np.rad2deg(r_print[3::4])

        x_print[1::2] = np.rad2deg(x_print[1::2])

        print("\n================================================")
        print(" Distribution System State Estimator")
        print("================================================")

        print("\nMeasurement Vector (z)\n")
        print(z_print)

        print("\nInitial State Vector (x0)\n")
        print(x_print)

        print("\nPredicted Measurement h(x)\n")
        print(h_print)

        print("\nResidual Vector r = z - h(x)\n")
        print(r_print)

        print("\nMeasurement Dimension :", len(self.z))
        print("State Dimension       :", len(self.x))

        print("================================================")

    ########################################################
    # Main Flow
    ########################################################

    def run(self, apply_sync_correction=False):

        print("\nBuilding measurement vector...")
        self.build_measurement_vector(apply_sync_correction=apply_sync_correction)

        print("Initializing state vector...")
        self.initialize_state(apply_sync_correction=apply_sync_correction)

        print("Predicting measurements...")
        self.predict_measurements()

        print("Computing residual...")
        self.compute_residual()

        self.summary()